# Project information
site_name: CONFIRE SHERLOCK
site_description: 'CONFIRE SHERLOCK Dokumentation'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.sherlock3.stueber.de'

# Copyright
copyright: © 2020 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.sherlock.de'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    feature:
        - tabs
        - instant
    palette:
        primary: 'indigo'
        accent: 'amber'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

extra:
  legal:
    - label: Impressum
      link: https://twitter.com/squidfunk
    - label: Datenschutz
      link: https://twitter.com/squidfunk

# Customization
extra_css:
    - assets/css/custom.css
    
# Extensions    
markdown_extensions:
    - admonition
  
# Navigation  
nav:
    - Überblick: index.md
    - Einführung: introduction.md
    - Was ist neu?: changelog.md
    - Voraussetzungen: requirements.md
    - So gehen Sie vor: howto.md
    - Tipps & Tricks: tips.md
    - Die API: api.md
    - Die CONSOLE: console.md